* Changelog

I hope the current card / log format is flexible enough to accommodate
upcoming changes.

In case a update to the org sources is needed, I'll add a changelog
entry with updating instructions.

** Develop

This update brings many changes to org-fc, including support for
multiple spacing algorithms.

Even if changes to configuration variables might be necessary, there
is no need to change any cards in org-mode files.

From now on, cards will include a =FC_ALGO= property. For
compatibility reasons, if a card doesn't have this property, it's
assumed that its algorithm is =sm2=, the original algorithm used by
org-fc.

While an attempt has been made to make this as uninvasive as possible,
and users who used the main-branch version of org-fc without changing
the configuration should be able to continue using this version
without any changes, users who customized the parameters of the sm2
algorithm are advised to take a look at the corresponding section of
this document.

Affected are the variables:
- ~org-fc-algorithm~
  Replaced with a list of algorithms
- ~org-fc-review-history-file~
  Now split into one file per algorithm (currently
  ~org-fc-algo-sm2-history-file~ and ~org-fc-algo-fsrs-history-file~)

Users who extended org-fc in some way that used the internal data
structures for cards and positions should refer to the *EIEIO*
section.

*** SM2 Algorithm

During the development of org-fc, some changes have been made
to the algorithm to approximate the algorithm used by Anki.

Previously, these were distinguished by different algorithm versions
(~sm2-v1~, ~sm2-v2~, ~sm2-v3~). To simplify the code, the changes
between these versions have been moved to configuration variables.

Users who choose to update to this version of org-fc
are advised to set these parameters in accordance to the version of
the algorithm they used previously or want to use now.

- ~org-fc-algo-sm2-hard-factor~, default 1.2

  Usually the next interval of a card is computed
  as ~(* current-interval next-ease)~.

  When set to a non-nil value, this factor will be used instead, for a
  next interval of ~(* current-interval hard-factor)~.

  | Version | Value |
  |---------+-------|
  | sm2-v1  |   nil |
  | sm2-v2  |   1.2 |
  | sm2-v3  |   1.2 |

- ~org-fc-algo-sm2-easy-bonus~, default 1.3

  To reduce the number of cards that are rated easy multiple times in
  a row, a bonus factor can be applied to cards rated easy.

  | Version | Value |
  |---------+-------|
  | sm2-v1  |   1.0 |
  | sm2-v2  |   1.0 |
  | sm2-v3  |   1.3 |

- ~org-fc-algo-again-box~, default 1

  By resetting the cards to box 1 instead of 0, even failed cards
  (rated "again") are not due for review immediately.

  This is closer to the behavior of Anki and with a non-zero value,
  it's possible to determine whether a SM2 card has not been reviewed
  yet by comparing its box to 0.

  | Version | Value |
  |---------+-------|
  | sm2-v1  |     0 |
  | sm2-v2  |     0 |
  | sm2-v3  |     1 |

*** EIEIO

Internal data structures for files, cards and positions
now use eieio classes instead of plists.

Code extending org-fc will need to replace ~plist-get~ with ~oref~ on
the relevant object.

*** Other
**** Skipping Cards

Before flipping a card, it can now be skipped with the =x= key.

**** Review Data

To allow for different spacing algorithms, a position now requires
only a due date and a name, the remaining entries of the review-data
table are stored in a plist.

They are mostly relevant for creating statistics.

During review, a much simpler procedure is used, passing the current
plist corresponding to a single row of the data-table to the spacing
algorithm and storing the new parameters it returns.

The next update of the cache then takes care of updating the data of
the object-based positions.

**** Performance

- The default find command lists only files containing flashcards.

- New variable ~org-fc-awk-find-command~ can be set to ~'ripgrep~
  if installed. This will speed up finding files with flashcards in
  large directories.

- For review history files with many entries, a significant amount of
  time was spent computing the "all" review statistics in the
  dashboard. By setting ~org-fc-awk-review-history-limit~ to an
  integer value, this can now be avoided.

**** ~org-fc-audio~

When used interactively, ~org-fc-audio-play~ now only lists audio
properties that are set on the current heading.

A new set of position-dependent properties has been added.

- =FC_AUDIO_BEFORE_SETUP_{poition}=
- =FC_AUDIO_AFTER_SETUP_{position}=
- =FC_AUDIO_AFTER_FLIP_{position}=

This allows e.g. playing an audio file both when showing the
front->back and when flipping the back->front side of a double-type
card, or playing different audio files for each position of a
cloze-type card.

~org-fc-audio~ now allows only one file to play at a time, killing the
playback process of the previous file if it is still active.

**** Cloze Cards

When reviewing a cloze-type card, point (the text cursor) is now moved
to the hole currently being reviewed.

For long cards, this ensures the hole is visible during review.

A new property =FC_CLOZE_CONTEXT= can be used to change the value of
size of the context shown for ~'contex~ cloze cards on a per-card basis.

**** Cache

Fixed a bug where the list of positions of cached cards could get
messed up over time.

**** Hooks

A new ~org-fc-after-rate-hook~ can be used e.g. for cleaning up
overlays created in a ~org-fc-before-setup-hook~.

A new ~org-fc-after-card-init-hook~ is run every time a new card is
created (initialized).

** 0.1.0
*** Added
- A ~org-fc-after-flip-hook~ that is run after a card is flipped
- Support for setting audio files to play after flipping a card via
  ~org-fc-audio-set-after-flip~
*** Fixed
- Reverting the dashboard buffer didn't work due to a missing function
  argument, this has been fixed
*** Renamed / Deprecated
- ~org-fc-audio-set-after~ -> ~org-fc-audio-set-after-setup~
- ~org-fc-audio-set-before~ -> ~org-fc-audio-set-before-setup~
- ~org-fc-audio-property-before~ -> ~org-fc-audio-before-setup-property~
- ~org-fc-audio-property-after~ -> ~org-fc-audio-after-setup-property~
*** Removed
- The "G" key binding in ~org-fc-dashboard-mode~ has been removed in
  favor of the default "g" ~revert-buffer~ binding
** 0.0.1
*** [2020-11-12 Thu]
- Removed ~(org-fc-filter-index index filter)~,
  replacing it with indexer specific functions
  ~(org-fc-awk-index paths &optional filter)~
  and
  ~(org-fc-cache-index paths &optional filter)~
- Added a defcustom ~org-fc-index-function~
  to support different indexers
- Added a prototype caching indexer
*** [2020-11-11 Wed]
**** Added
The dashboard now includes a forecast of how many cards will be due
during the next day, week (+7 days) or month (+30 days).
**** Changed
- All dashboard functions were extracted to a separate file
- ~org-fc-stats~ was renamed to ~org-fc-dashboard-stats~
- ~org-fc--hashtable-to-alist~ was renamed to ~org-fc-dashboard--hashtable-to-alist~
- ~org-fc-context-dashboard~ was renamed to ~org-fc-dashboard-context~
- ~org-fc-review-dashboard-context~ was renamed to ~org-fc-dashboard-review~
*** [2020-09-09 Wed]
Org-fc now supports nested flashcards.

**** Changed
- It's now possible to mark child headings of flashcards as a flashcards
- When flipping a card, child headings (except the "Back" heading)
  remain collapsed
- Subheadings are ignored when searching for holes of cloze cards
*** [2020-07-16 Thu]
**** Changed
- Suspending a card during review now removes all other positions of
  it from the current session, to avoid reviewing suspended cards
*** [2020-07-08 Wed]
**** Changed
The awk index now also includes the headline text of each card.

This will be useful for building a ~tabulated-list-mode~ based card
overview.
*** [2020-07-06 Mon]
**** Added
- ~org-fc-suspend-tree~ for suspending all cards in a subtree
**** Changed
- unsuspending overdue cards doesn't reset their review data anymore
*** [2020-07-04 Sat]
**** Added
- ~org-fc-review-edit~ (bound to ~p~) pauses the review for editing
  the current card. A new mode ~org-fc-review-edit-mode~ adds
  keybindings for resuming & quitting the review.
*** [2020-07-03 Fri]
**** Changed
- By default, failed cards are appended to the end of the review session.
  This can be configured via ~org-fc-append-failed-cards~
- ~org-fc-map-cards~ takes an optional ~scope~ argument,
  similar to ~org-map-entries~.
**** Added
- ~org-fc-unsuspend-tree~ unsuspends all cards in the subtree at point
*** [2020-07-02 Thu]
**** Changed
- ~org-fc-review-rate-card~ was renamed to ~org-fc-review-rate~
*** [2020-07-01 Wed]
**** Changed
- The review history file is only written once per review,
  as a first step towards implementing a "undo-rating" command
*** [2020-06-29 Mon]
**** Added
- Shuffling of positions for the review can be disabled
  by setting ~org-fc-shuffle-positions~ to ~nil~
**** Changed
- Error messages from shell commands are promoted
*** [2020-06-28 Sun]
**** Added
- ~org-fc-before-review-hook~ that runs when a review session is started
*** [2020-06-26 Fri]
**** Changed
- Messages are not inhibited during review
- Whitelisted drawers are expanded during review
**** Added
- A ~org-fc-after-review-hook~ that runs when the review ends / is quit
- ~org-fc-keymap-hint~ extension
- ~org-fc-audio~ extension
*** [2020-06-25 Thu]
**** Added
- ~SCHEDULED: ...~, ~DEADLINE: ...~ timestamps are hidden during
  review
- Drawers in ~org-fc-drawer-whitelist~ are not hidden during review
**** Changed
- During the review process, two minor modes are used instead of two
  hydras
*** [2020-05-24 Sun]
**** Changed
- Include file information in card index
- Maintain order of positions in a card when shuffling
*** [2020-05-22 Fri]
**** Changed
- Exit hydra when review is started
*** [2020-05-08 Fri]
**** Changed
- Per-context dashboard
- Improve org-indent of cards
- Use special "fc-demo" tag for demo cards
- Move opening of flip/rating hydras to main review loop
*** [2020-05-01 Fri]
**** Internal
The AWK scripts now generate S-expressions instead of CSV tables, this
way ~read~ can be used to parse the data instead of relying on a set
of custom parsing functions.

This also allows passing more complex data structures from AWK to
org-fc.
*** [2020-04-29 Wed]
Implemented a new version of the spacing algorithm (SM2) that's used
by org-fc.

The only difference is in how the next interval for cards rated as
"hard" is calculate.

The initial version (~'sm2-v1~) would decrease the ease factor by
0.15, then calculate the next interval by multiplying the previous
interval with the new ease factor.

In the new version (~'sm2-v2~), the interval is always multiplied by a
factor of 1.2, similar to the version of SM2 used by Anki.

~org-fc-algorithm~ can be used to set which version of the
algorithm should be used, defaulting to ~'sm2-v1~.

Once I have evaluated the performance of the new algorithm,
the default version will change to ~'sm2-v2~.
*** [2020-04-12 Sun]
**** Added
- =text-input= card type
*** [2020-02-08 Sat]
**** Changed
- Add a "Z" suffix to all ISO8601 timestamps
**** Added
- A function to estimate the number of reviews in the next n days
*** [2020-02-03 Mon]
**** Internal
- ~org-fc-due-positions-for-paths~ now shuffles the lists of positions
  using an Emacs Lisp function instead of depending on =shuf=
- All awk-indexer functions now use ~gawk~ instead of ~awk~
